apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: web-app
type: Opaque
stringData:
  # stringData permette di inserire il testo in chiaro nel file YAML, 
  # Kubernetes provvederà alla codifica base64 automatica
  MYSQL_ROOT_PASSWORD: "Inserisci password admin"
  MYSQL_DATABASE: "web-app"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "Inserisci password user"
  # Nomi usati dal Backend Node.js
  MARIADB_USER: "user"
  MARIADB_PASSWORD: "Inserisci password user"
  MARIADB_DATABASE: "web-app"
  

