apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: web-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  MYSQL_DATABASE: "web-app"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  MARIADB_USER: "user"
  MARIADB_PASSWORD: "${MYSQL_PASSWORD}"
  MARIADB_DATABASE: "web-app"